spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.core: INFO

management:
  endpoints:
    web:
      expose: health

server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-alias: tomcat
#  port: 8443
